# -*- coding: utf-8 -*-
"""MENU FOR A HOTEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPePkwMDY-HZSHtjMuiHc0K9aTSS8pR9
"""

# Define menu of Restaurant
menu = {
    'pizza': 40,
    'pasta': 50,
    'tea': 80,
    'burger': 150,
    'coffee': 124
}

# Greet the customer
print("Welcome to our restaurant!")
print("Menu: pizza: Rs40, pasta: Rs50, tea: Rs80, burger: Rs150, coffee: Rs124")

# Initialize order total
order_total = 0

# Function to take order
def take_order():
    global order_total
    while True:
        # Ask the customer for an item
        item = input("Enter the name of the item you want (or 'done' to finish): ").lower()

        # Exit the loop if the customer is done ordering
        if item == 'done':
            break

        # Check if the item is in the menu
        if item in menu:
            order_total += menu[item]
            print(f"Your {item} has been added to your order.")
        else:
            print(f"Sorry, {item} is not on the menu. Please choose from the menu.")

# Calling the function
take_order()

#  total cost
if order_total > 0:
    print(f"\nYour total order cost is: Rs{order_total}")
else:
    print("\nYou haven't ordered anything.")