# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqGO8t9rQIa1AEVKGveqfkkd-ds8KCct
"""

try:
    num = int(input("Enter a number: "))
    num2 = int(input("Enter a number: "))

    result = num / num20
    print("Result:", int(result))
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except ValueError:
    print("Error: Invalid input, please enter a number.")



try:
    number = int(input("Enter a number: "))
    print(f"The square of {number} is {number ** 2}")
except ValueError:
    print("Error: You must enter a valid number.")

try:
    nume = int(input("Enter the numerator: "))
    denumi = int(input("Enter the denominator: "))
    result = nume / denumi
    print(f"The result of the division is: {result}")
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except Valu1eError:
    print("Error: Invalid input. Please enter numeric values.")