# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

colors = ['red', 'green', 'blue']
for color in colors:
    print(color)

name = "shoaib"
for char in name:
    print(char)

for number in range(1,6):
  print(number)

name = "MahNoor"
for char in name:
  print(char)

fruits = ["Apple", 'Banana', 'Orange', "Malta"]
for char in fruits:
  print(char)

num = (1,2,3,4,5,6,7,8)
for i in num:
  print(i)

person = {
    'Name': 'Shoaib',
    'City': 'Bahawalnagar',
    'Class': 'BSCS',
}

for i in person:
    print(f"{i}: {person[i]}")

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for row in matrix:
  for element in row:
    print(element)

for i in range(1,5):
  for j in range(i):
    print(i + j)

color = ['red', 'orange', 'blue']
shape = ['Circle', 'square', 'rectangle']

for i in color:
  for j in shape:
    print(f"{i} : {j}")

for num in range(2, 11):
  for div in range(2, num):
    if num % 2 == 0:
      break
    else:
      print(f"{num} is a Prime Number")