name = input("Enter your name: ")
print(name)
print(type(name))
age = int(input("Enter your age: "))
print(age)
print(type(age)) 
fruit= input("Enter your favuorite fruit: ")
print(fruit)
print(type(fruit))
vegetable= input("Enter your favuorite vegetable: ")
print(vegetable)
print(type(vegetable))
color= input("Enter your favuorite color: ")
print(color)
print(type(color))
price = float(input("Enter the price of dress? "))
print(price)
print(type(price))
CGPA = float(input("Enter your semester CGPA? "))
print(CGPA)
print(type(CGPA))
Team = int(input("How many players in the team? "))
print(Team)
print(type(Team))
band = int(input("how many members in the band? "))
print(Team)
print(type(Team))
city= input("Enter your favuorite city: ")
print(city)
print(type(city))
University= input("In which University you doing your bachelor: ")
print(University)         
print(type(University))    
semester = int(input("In which semester you are? "))   
print(semester)            
print(type(semester))
distance = float(input("how much distance you cover in one round: "))
print(distance)
print(type(distance))
num_of_students = int(input("how mant students in your class? "))
print(num_of_students)
print(type(num_of_students))
email = input("Enter your email: ")
print(email)
print(type(email))
country = input("In which country you live: ")
print(country)
print(type(country))
shose = int(input("how many pair of shoses you have? "))
print(shose)
print(type(shose))
adult = bool(input("You are 18+: "))
print(adult)
print(type(adult))
is_student = bool(input("Are you student? "))
print(is_student)
print(type(is_student))
month = int(input("Enter your Brithday month: "))
print(month)
print(type(month))
date = int(input("Enter your date of brith: "))
print(date)
print(type(date))
quantity = float(input("How much sugar you want to buy? "))
print(quantity)
print(type(quantity))
account_number = int(input("Enter your account_number: "))
print(account_number)
print(type(account_number))
full_name = input("Enter your full name: ")
print(full_name)
print(type(full_name))
district = input("Enter your district: ")
print(district)
print(type(district))
members = int(input("Enter the number of your family members: "))
print(members)
print(type(members))
is_sale = bool(input("You want to sale your car? "))
print(is_sale)
print(type(is_sale))
percentage = float(input("Enter the percentage of your intermadiate: "))
print(percentage)
print(type(percentage))
friends = int(input("How many friends you have? "))
print(friends)
print(type(friends))
sport = input("Enter your favourite sport: ")
print(sport)
print(type(sport))
a = 20
print(type(a))
b = "Nimra"
print(type(b))
c = 3.14
print(type(c))
d = True
print(type(d))
